-- LIST OF ALL SUCCESSFULL RIDES.
SELECT * FROM SUCCESSFULL_BOOKINGS; 

-- AVERAGE DISTANCE TRAVELLED BY EACH VEHICLE TYPE.
SELECT * FROM AVERAGE_DISTANCE_PER_VEHICLE_TYPE;

-- THE TOTAL NUMBER OF RIDES CANCELLED BY CUSTOMERS.
SELECT * FROM CANCELLED_RIDES_BY_CUSTOMERS;

-- TOP 5 CUSTOMERS ALONG WITH THEIR NUMBER OF RIDES
SELECT * FROM TOP_5_CUSTOMERS;

-- RIDES CANCELLED BY DRIVERS DUE TO PERSONAL AND CAR RELATED ISSUES
SELECT * FROM CANCELLED_BY_DRIVERS_P_C_ISSUES;

-- THE MAXIMUM AND MININMUM RATINGS RECEIVED BY PRIME-SEDAN DRIVERS.
SELECT * FROM MAX_MIN_DRIVER_RATINGS_PRIMESEDAN;

-- THE LIST OF ALL RIDES WHO'S PAYMENT WAS MADE THOUGH UPI.
SELECT * FROM UPI_PAYMENTS;

-- AVERAGE OF RATING GIVEN BY CUSTOMERS FOR EACH VEHICLE TYPE.
SELECT * FROM CUSTOMER_RATING_PER_VEHICLE_TYPE;

-- TOTAL BOOKING VALUE FOR THE RIDES WHICH WERE SUCCESSFULL.
SELECT * FROM TOTAL_BOOKING_VALUE_FOR_SUCCESSFUL_RIDES;

-- THE BOOKING ID OF INCOMPLETE RIDES AND THEIR REASONS.
SELECT * FROM INCOMPLETE_RIDES_REASON;

-- THE DISTRUBUTION OF REASONS OF CANCELLATION.
SELECT INCOMPLETE_RIDES_REASON,COUNT(BOOKING_ID) AS CANCELLATION_COUNT
FROM INCOMPLETE_BOOKINGS 
GROUP BY 1; 