CREATE DATABASE OLA_SQL;
USE OLA_SQL;

--
SELECT * FROM BOOKINGS
LIMIT 5;

--
ALTER TABLE BOOKINGS
RENAME COLUMN `ï»¿Date` TO BOOKING_DATE;
--

-- I WILL BE CREATING VIEW FOR EACH QUESTION TO MAKE RETRIVING BECOMES SIMPLE.

-- 1. Retrieve all successful bookings:
CREATE VIEW SUCCESSFULL_BOOKINGS AS
SELECT * FROM BOOKINGS
WHERE BOOKING_STATUS = 'Success';
-- I HAVE CREATED A VIEW FOR THAT QUERY SO THAT THE QUERY LOOKS MORE SIMPLIFIED WHENEVER YOU RETRIEVE IT.
SELECT * FROM SUCCESSFULL_BOOKINGS; 
-- THERE ARE TOTAL OF '63967' SUCCESSFULL BOOKINGS.
--
-- 2. Find the average ride distance for each vehicle type:
CREATE VIEW AVERAGE_DISTANCE_PER_VEHICLE_TYPE AS
SELECT VEHICLE_TYPE,ROUND(AVG(RIDE_DISTANCE),2) AS AVG_RIDE_DISTANCE
FROM BOOKINGS
GROUP BY VEHICLE_TYPE;
-- VIEW FOR THIS QUERY.
SELECT * FROM AVERAGE_DISTANCE_PER_VEHICLE_TYPE;
-- PRIME SEDAN HAS THE HIGHEST AVERAGE RIDE DISTANCE (15.76 KMS) FOLLOWED BY E-BIKE (15.58 KMS)
-- WHICH MEANS ON AN AVERAGE EVERY RIDE OF PRIME SEDAN WILL COVER THE DISTANCE OF 15.76 KMS.
--
-- 3. Get the total number of canceled rides by customers:
CREATE VIEW CANCELLED_RIDES_BY_CUSTOMERS AS
SELECT COUNT(*) AS CANCELLED_RIDES
FROM BOOKINGS
WHERE BOOKING_STATUS = 'Canceled by Customer';
--
SELECT * FROM CANCELLED_RIDES_BY_CUSTOMERS;
-- THERE ARE TOTAL OF 10499 RIDES WHICH ARE CANCELLED BY CUSTOMERS.
--
-- 4. List the top 5 customers who booked the highest number of rides:
CREATE VIEW TOP_5_CUSTOMERS AS 
SELECT CUSTOMER_ID,COUNT(*) AS BOOKING_COUNT
FROM BOOKINGS
GROUP BY CUSTOMER_ID
ORDER BY BOOKING_COUNT DESC
LIMIT 5;
--
SELECT * FROM TOP_5_CUSTOMERS;
-- CUSTOMER WITH ID>>CID954071 HAS THE HIGHEST NUMBER RIDES (5).
-- CUSTOMERS WITH ID>>CID539191,CID189965,CID268274,CID952434 HAS TOTAL BOOKING COUNT OF 4 EACH.
--
-- 5. Get the number of rides canceled by drivers due to personal and car-related issues:
CREATE VIEW CANCELLED_BY_DRIVERS_P_C_ISSUES AS
SELECT COUNT(*) AS RIDES_CANCELLED FROM BOOKINGS
WHERE CANCELED_RIDES_BY_DRIVER = 'Personal & Car related issue';
-- 
SELECT * FROM CANCELLED_BY_DRIVERS_P_C_ISSUES;
-- THERE ARE TOTAL OF 6542 RIDES CANCELLED BY DRIVERS DUE TO Personal & Car related issue.
--
-- 6. Find the maximum and minimum driver ratings for Prime Sedan bookings:
CREATE VIEW MAX_MIN_DRIVER_RATINGS_PRIMESEDAN AS
SELECT VEHICLE_TYPE,MAX(DRIVER_RATINGS) AS MAX_RATINGS,
MIN(DRIVER_RATINGS) AS MIN_RATINGS
FROM BOOKINGS
WHERE VEHICLE_TYPE = 'Prime Sedan'
GROUP BY VEHICLE_TYPE;
--
SELECT * FROM MAX_MIN_DRIVER_RATINGS_PRIMESEDAN;
-- VEHICLE TYPE 'PRIME SEDAN' HAS A MAXIMUM DRIVER RATING OF 5 AND A MINIMUM DRIVER RATING OF 3.
--
-- 7. Retrieve all rides where payment was made using UPI:
CREATE VIEW UPI_PAYMENTS AS
SELECT BOOKING_ID FROM BOOKINGS
WHERE PAYMENT_METHOD = 'UPI';
--
SELECT * FROM UPI_PAYMENTS;
-- I HAVE RETRIVED THE BOOKING ID'S WHOSE PAYMENT WERE MADE THROUGH UPI.
-- THERE WERE TOTAL OF 25881 PAYMENTS WHICH WERE MADE THROUGH UPI.
--
-- 8. Find the average customer rating per vehicle type:
CREATE VIEW CUSTOMER_RATING_PER_VEHICLE_TYPE AS
SELECT VEHICLE_TYPE,ROUND(AVG(CUSTOMER_RATING),2) AS AVG_CUSOMER_RATINGS
FROM BOOKINGS
GROUP BY VEHICLE_TYPE;
-- 
SELECT * FROM CUSTOMER_RATING_PER_VEHICLE_TYPE;
-- PRIME PLUS HAS THE HIGHEST AVERAGE CUSTOMER RATING OF 4.01 AMONG ALL VEHICLE TYPES.   
-- BIKE AND EBIKE HAVE THE LOWEST AVERAGE CUSTOMER RATINGS OF 3.99.   
-- PRIME SEDAN, PRIME SUV, MINI, AND AUTO ALL HAVE AN AVERAGE CUSTOMER RATING OF 4. 
--
-- 9. Calculate the total booking value of rides completed successfully:
CREATE VIEW TOTAL_BOOKING_VALUE_FOR_SUCCESSFUL_RIDES AS 
SELECT SUM(BOOKING_VALUE) AS TOTAL_BOOKING_VALUE
FROM BOOKINGS
WHERE BOOKING_STATUS = 'SUCCESS';
--
SELECT * FROM TOTAL_BOOKING_VALUE_FOR_SUCCESSFUL_RIDES;
-- TOTAL BOOKING VALUE FOR THE SUCCESSFUL RIDES ARE 35080467.
--
-- 10. List all incomplete rides along with the reason:
CREATE VIEW INCOMPLETE_BOOKINGS AS 
SELECT BOOKING_ID,INCOMPLETE_RIDES_REASON
FROM BOOKINGS
WHERE INCOMPLETE_RIDES = 'YES';
-- 
SELECT INCOMPLETE_RIDES_REASON,COUNT(BOOKING_ID) AS CANCELLATION_COUNT
FROM INCOMPLETE_BOOKINGS 
GROUP BY 1; 
-- I FILTERED THE VIEW TO KNOW SOME MORE INSIGHTS REGARDING THE CANCELLATION.
--
-- CUSTOMER DEMAND IS THE LEADING REASON FOR INCOMPLETE RIDES, ACCOUNTING FOR 1,601 CANCELLATIONS.   
-- VEHICLE BREAKDOWN IS THE SECOND HIGHEST REASON, RESULTING IN 1,591 CANCELLATIONS.   
-- OTHER ISSUE ACCOUNTS FOR THE LOWEST REASON WITH 734 CANCELLATIONS.